// Auto-generated by the Supabase CLI/MCP (`supabase gen types typescript`).
// Covers the ENTIRE project — both the concierge desk's tables
// (requests, staff, contacts, events, event_media) and the workplace
// mediation platform's tables (profiles, organizations, cases, ...), since
// they share one Supabase project. Regenerate after any schema change:
//
//   supabase gen types typescript --project-id dgxmouzxgbiigzmtalwo > types/supabase.ts
//
// Do not hand-edit — see supabase/migrations/ for the source of truth.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      agreements: {
        Row: {
          case_id: string
          created_at: string
          id: string
          share_with_hr: boolean
          signed_at: string | null
          status: Database["public"]["Enums"]["agreement_status"]
          terms_content: string
          updated_at: string
        }
        Insert: {
          case_id: string
          created_at?: string
          id?: string
          share_with_hr?: boolean
          signed_at?: string | null
          status?: Database["public"]["Enums"]["agreement_status"]
          terms_content: string
          updated_at?: string
        }
        Update: {
          case_id?: string
          created_at?: string
          id?: string
          share_with_hr?: boolean
          signed_at?: string | null
          status?: Database["public"]["Enums"]["agreement_status"]
          terms_content?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "agreements_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "cases"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          created_at: string
          entity_id: string | null
          entity_name: string
          id: string
          payload: Json | null
          user_id: string | null
        }
        Insert: {
          action: string
          created_at?: string
          entity_id?: string | null
          entity_name: string
          id?: string
          payload?: Json | null
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          entity_id?: string | null
          entity_name?: string
          id?: string
          payload?: Json | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      case_participants: {
        Row: {
          case_id: string
          created_at: string
          id: string
          is_consent_given: boolean
          party_role: string | null
          profile_id: string
        }
        Insert: {
          case_id: string
          created_at?: string
          id?: string
          is_consent_given?: boolean
          party_role?: string | null
          profile_id: string
        }
        Update: {
          case_id?: string
          created_at?: string
          id?: string
          is_consent_given?: boolean
          party_role?: string | null
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "case_participants_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "case_participants_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cases: {
        Row: {
          assigned_mediator_id: string | null
          case_number: string
          created_at: string
          description: string | null
          hr_representative_id: string | null
          id: string
          is_confidential: boolean
          organization_id: string | null
          priority: Database["public"]["Enums"]["case_priority"]
          status: Database["public"]["Enums"]["case_status"]
          title: string
          updated_at: string
        }
        Insert: {
          assigned_mediator_id?: string | null
          case_number: string
          created_at?: string
          description?: string | null
          hr_representative_id?: string | null
          id?: string
          is_confidential?: boolean
          organization_id?: string | null
          priority?: Database["public"]["Enums"]["case_priority"]
          status?: Database["public"]["Enums"]["case_status"]
          title: string
          updated_at?: string
        }
        Update: {
          assigned_mediator_id?: string | null
          case_number?: string
          created_at?: string
          description?: string | null
          hr_representative_id?: string | null
          id?: string
          is_confidential?: boolean
          organization_id?: string | null
          priority?: Database["public"]["Enums"]["case_priority"]
          status?: Database["public"]["Enums"]["case_status"]
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cases_assigned_mediator_id_fkey"
            columns: ["assigned_mediator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cases_hr_representative_id_fkey"
            columns: ["hr_representative_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cases_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      contacts: {
        Row: {
          address: string | null
          created_at: string
          email: string | null
          id: number
          label: string
          phone: string | null
          sort_order: number
          updated_at: string
          whatsapp: string | null
        }
        Insert: {
          address?: string | null
          created_at?: string
          email?: string | null
          id?: never
          label: string
          phone?: string | null
          sort_order?: number
          updated_at?: string
          whatsapp?: string | null
        }
        Update: {
          address?: string | null
          created_at?: string
          email?: string | null
          id?: never
          label?: string
          phone?: string | null
          sort_order?: number
          updated_at?: string
          whatsapp?: string | null
        }
        Relationships: []
      }
      documents: {
        Row: {
          case_id: string
          created_at: string
          file_name: string
          file_path: string
          id: string
          is_confidential: boolean
          uploaded_by: string | null
        }
        Insert: {
          case_id: string
          created_at?: string
          file_name: string
          file_path: string
          id?: string
          is_confidential?: boolean
          uploaded_by?: string | null
        }
        Update: {
          case_id?: string
          created_at?: string
          file_name?: string
          file_path?: string
          id?: string
          is_confidential?: boolean
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "documents_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      event_media: {
        Row: {
          created_at: string
          event_id: number
          id: number
          media_type: string
          sort_order: number
          storage_path: string
        }
        Insert: {
          created_at?: string
          event_id: number
          id?: never
          media_type: string
          sort_order?: number
          storage_path: string
        }
        Update: {
          created_at?: string
          event_id?: number
          id?: never
          media_type?: string
          sort_order?: number
          storage_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "event_media_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          created_at: string
          description: string | null
          event_date: string | null
          id: number
          location: string | null
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          event_date?: string | null
          id?: never
          location?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          event_date?: string | null
          id?: never
          location?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      mediator_notes: {
        Row: {
          author_id: string | null
          case_id: string
          created_at: string
          id: string
          is_private_to_mediator: boolean
          note_content: string
        }
        Insert: {
          author_id?: string | null
          case_id: string
          created_at?: string
          id?: string
          is_private_to_mediator?: boolean
          note_content: string
        }
        Update: {
          author_id?: string | null
          case_id?: string
          created_at?: string
          id?: string
          is_private_to_mediator?: boolean
          note_content?: string
        }
        Relationships: [
          {
            foreignKeyName: "mediator_notes_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mediator_notes_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "cases"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          contact_email: string | null
          created_at: string
          id: string
          industry: string | null
          name: string
        }
        Insert: {
          contact_email?: string | null
          created_at?: string
          id?: string
          industry?: string | null
          name: string
        }
        Update: {
          contact_email?: string | null
          created_at?: string
          id?: string
          industry?: string | null
          name?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          email: string
          full_name: string
          id: string
          organization_id: string | null
          phone: string | null
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          email: string
          full_name: string
          id: string
          organization_id?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          organization_id?: string | null
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      requests: {
        Row: {
          completed_at: string | null
          created_at: string
          decision_note: string | null
          details: Json
          dob: string
          email: string
          fee: number | null
          id: number
          name: string
          notified_at: string | null
          payment_method: string | null
          phone: string
          service_label: string | null
          status: string
          summary: string
          ticket: string | null
          type: string
          type_label: string
          updated_at: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          decision_note?: string | null
          details?: Json
          dob: string
          email: string
          fee?: number | null
          id?: never
          name: string
          notified_at?: string | null
          payment_method?: string | null
          phone: string
          service_label?: string | null
          status?: string
          summary: string
          ticket?: string | null
          type: string
          type_label: string
          updated_at?: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          decision_note?: string | null
          details?: Json
          dob?: string
          email?: string
          fee?: number | null
          id?: never
          name?: string
          notified_at?: string | null
          payment_method?: string | null
          phone?: string
          service_label?: string | null
          status?: string
          summary?: string
          ticket?: string | null
          type?: string
          type_label?: string
          updated_at?: string
        }
        Relationships: []
      }
      sessions: {
        Row: {
          case_id: string
          created_at: string
          id: string
          location_or_link: string | null
          mediator_id: string | null
          scheduled_end: string
          scheduled_start: string
          session_type: Database["public"]["Enums"]["session_type"]
          status: Database["public"]["Enums"]["session_status"]
        }
        Insert: {
          case_id: string
          created_at?: string
          id?: string
          location_or_link?: string | null
          mediator_id?: string | null
          scheduled_end: string
          scheduled_start: string
          session_type: Database["public"]["Enums"]["session_type"]
          status?: Database["public"]["Enums"]["session_status"]
        }
        Update: {
          case_id?: string
          created_at?: string
          id?: string
          location_or_link?: string | null
          mediator_id?: string | null
          scheduled_end?: string
          scheduled_start?: string
          session_type?: Database["public"]["Enums"]["session_type"]
          status?: Database["public"]["Enums"]["session_status"]
        }
        Relationships: [
          {
            foreignKeyName: "sessions_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sessions_mediator_id_fkey"
            columns: ["mediator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      staff: {
        Row: {
          created_at: string
          is_admin: boolean
          user_id: string
        }
        Insert: {
          created_at?: string
          is_admin?: boolean
          user_id: string
        }
        Update: {
          created_at?: string
          is_admin?: boolean
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_add_event_media: {
        Args: {
          p_event_id: number
          p_media_type: string
          p_sort_order?: number
          p_storage_path: string
        }
        Returns: {
          created_at: string
          event_id: number
          id: number
          media_type: string
          sort_order: number
          storage_path: string
        }
      }
      admin_delete_contact: { Args: { p_id: number }; Returns: undefined }
      admin_delete_event: { Args: { p_id: number }; Returns: undefined }
      admin_delete_event_media: { Args: { p_id: number }; Returns: undefined }
      admin_list_staff: {
        Args: never
        Returns: {
          created_at: string
          email: string
          is_admin: boolean
          user_id: string
        }[]
      }
      admin_remove_staff: { Args: { p_user_id: string }; Returns: undefined }
      admin_set_staff_admin: {
        Args: { p_is_admin: boolean; p_user_id: string }
        Returns: undefined
      }
      admin_upsert_contact: {
        Args: {
          p_address: string
          p_email: string
          p_id: number
          p_label: string
          p_phone: string
          p_sort_order?: number
          p_whatsapp: string
        }
        Returns: {
          address: string | null
          created_at: string
          email: string | null
          id: number
          label: string
          phone: string | null
          sort_order: number
          updated_at: string
          whatsapp: string | null
        }
      }
      admin_upsert_event: {
        Args: {
          p_description: string
          p_event_date: string
          p_id: number
          p_location: string
          p_title: string
        }
        Returns: {
          created_at: string
          description: string | null
          event_date: string | null
          id: number
          location: string | null
          title: string
          updated_at: string
        }
      }
      is_admin: { Args: never; Returns: boolean }
      is_staff: { Args: never; Returns: boolean }
      list_contacts: {
        Args: never
        Returns: {
          address: string | null
          created_at: string
          email: string | null
          id: number
          label: string
          phone: string | null
          sort_order: number
          updated_at: string
          whatsapp: string | null
        }[]
      }
      list_events: {
        Args: never
        Returns: {
          created_at: string
          description: string
          event_date: string
          id: number
          location: string
          media: Json
          title: string
          updated_at: string
        }[]
      }
      med_caller_org_id: { Args: never; Returns: string }
      med_case_org_matches_caller: {
        Args: { p_case_id: string }
        Returns: boolean
      }
      med_current_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      med_is_admin: { Args: never; Returns: boolean }
      med_is_case_hr_rep: { Args: { p_case_id: string }; Returns: boolean }
      med_is_case_mediator: { Args: { p_case_id: string }; Returns: boolean }
      med_is_case_participant: { Args: { p_case_id: string }; Returns: boolean }
      med_profile_linked_to_my_cases: {
        Args: { p_profile_id: string }
        Returns: boolean
      }
      med_storage_case_id: { Args: { p_name: string }; Returns: string }
      pay_request: {
        Args: { p_id: number; p_method: string }
        Returns: {
          completed_at: string | null
          created_at: string
          decision_note: string | null
          details: Json
          dob: string
          email: string
          fee: number | null
          id: number
          name: string
          notified_at: string | null
          payment_method: string | null
          phone: string
          service_label: string | null
          status: string
          summary: string
          ticket: string | null
          type: string
          type_label: string
          updated_at: string
        }
      }
      request_type_label: { Args: { p_type: string }; Returns: string }
      staff_approve_request: {
        Args: { p_fee?: number; p_id: number }
        Returns: {
          completed_at: string | null
          created_at: string
          decision_note: string | null
          details: Json
          dob: string
          email: string
          fee: number | null
          id: number
          name: string
          notified_at: string | null
          payment_method: string | null
          phone: string
          service_label: string | null
          status: string
          summary: string
          ticket: string | null
          type: string
          type_label: string
          updated_at: string
        }
      }
      staff_complete_request: {
        Args: { p_id: number }
        Returns: {
          completed_at: string | null
          created_at: string
          decision_note: string | null
          details: Json
          dob: string
          email: string
          fee: number | null
          id: number
          name: string
          notified_at: string | null
          payment_method: string | null
          phone: string
          service_label: string | null
          status: string
          summary: string
          ticket: string | null
          type: string
          type_label: string
          updated_at: string
        }
      }
      staff_list_requests: {
        Args: never
        Returns: {
          completed_at: string | null
          created_at: string
          decision_note: string | null
          details: Json
          dob: string
          email: string
          fee: number | null
          id: number
          name: string
          notified_at: string | null
          payment_method: string | null
          phone: string
          service_label: string | null
          status: string
          summary: string
          ticket: string | null
          type: string
          type_label: string
          updated_at: string
        }[]
      }
      staff_reject_request: {
        Args: { p_id: number; p_note?: string }
        Returns: {
          completed_at: string | null
          created_at: string
          decision_note: string | null
          details: Json
          dob: string
          email: string
          fee: number | null
          id: number
          name: string
          notified_at: string | null
          payment_method: string | null
          phone: string
          service_label: string | null
          status: string
          summary: string
          ticket: string | null
          type: string
          type_label: string
          updated_at: string
        }
      }
      submit_request: {
        Args: {
          p_dob: string
          p_email: string
          p_fields: Json
          p_name: string
          p_phone: string
          p_type: string
        }
        Returns: {
          completed_at: string | null
          created_at: string
          decision_note: string | null
          details: Json
          dob: string
          email: string
          fee: number | null
          id: number
          name: string
          notified_at: string | null
          payment_method: string | null
          phone: string
          service_label: string | null
          status: string
          summary: string
          ticket: string | null
          type: string
          type_label: string
          updated_at: string
        }
      }
      track_request: {
        Args: { p_dob: string; p_name: string; p_ticket: string }
        Returns: {
          completed_at: string | null
          created_at: string
          decision_note: string | null
          details: Json
          dob: string
          email: string
          fee: number | null
          id: number
          name: string
          notified_at: string | null
          payment_method: string | null
          phone: string
          service_label: string | null
          status: string
          summary: string
          ticket: string | null
          type: string
          type_label: string
          updated_at: string
        }[]
      }
      whoami: {
        Args: never
        Returns: {
          email: string
          is_admin: boolean
          user_id: string
        }[]
      }
    }
    Enums: {
      agreement_status:
        | "draft"
        | "under_review"
        | "signed"
        | "breached"
        | "archived"
      case_priority: "low" | "medium" | "high" | "urgent"
      case_status:
        | "intake"
        | "pre_mediation"
        | "joint_session"
        | "agreement_drafting"
        | "completed"
        | "cancelled"
      session_status:
        | "scheduled"
        | "in_progress"
        | "completed"
        | "rescheduled"
        | "cancelled"
      session_type:
        | "intake_hr"
        | "pre_mediation_1on1"
        | "joint_facilitation"
        | "follow_up"
      user_role: "admin" | "hr_client" | "mediator" | "participant"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database["public"]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof Database
}
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof Database
}
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof Database
}
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof Database
}
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      agreement_status: [
        "draft",
        "under_review",
        "signed",
        "breached",
        "archived",
      ],
      case_priority: ["low", "medium", "high", "urgent"],
      case_status: [
        "intake",
        "pre_mediation",
        "joint_session",
        "agreement_drafting",
        "completed",
        "cancelled",
      ],
      session_status: [
        "scheduled",
        "in_progress",
        "completed",
        "rescheduled",
        "cancelled",
      ],
      session_type: [
        "intake_hr",
        "pre_mediation_1on1",
        "joint_facilitation",
        "follow_up",
      ],
      user_role: ["admin", "hr_client", "mediator", "participant"],
    },
  },
} as const
